language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
  - php: 7.3

branches:
  only:
  - master

services:
    - memcached
    - mysql

cache:
    directories:
      - "$HOME/.composer/cache"

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install apache2 libapache2-mod-fastcgi
  - sudo apt-get -y install libmemcached-dev
  - pecl channel-update pecl.php.net
  - travis_retry composer self-update
  - composer install
  - gem install mime-types -v 2.99.1
  - mysql -e "CREATE USER 'ragnaservice'@'localhost' IDENTIFIED BY 'ragnaservice';"
  - mysql -e "CREATE DATABASE ragnaservice;"
  - mysql -e "GRANT ALL PRIVILEGES ON ragnaservice.* TO 'ragnaservice'@'localhost';"
  - mysql -e "CREATE USER 'ragnarok'@'localhost' IDENTIFIED BY 'ragnarok';"
  - mysql -e "CREATE DATABASE ragnarok;"
  - mysql -e "GRANT ALL PRIVILEGES ON ragnarok.* TO 'ragnarok'@'localhost';"
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf 2>/dev/null || true
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  - git clone --depth 1 https://github.com/HerculesWS/Hercules.git tmp
  - mysql -uragnarok -pragnarok ragnarok < tmp/sql-files/main.sql
  - mysql -uragnarok -pragnarok ragnarok < tmp/sql-files/logs.sql
  - rm -rf tmp

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - vendor/bin/codacycoverage clover coverage.xml
